## Camera Callibration

In [7]:
import cv2
import numpy as np
import glob
import matplotlib as plt

# Define chessboard size (number of inside corners per row and column)
chessboard_size = (7, 9)

# Prepare object points (0,0,0), (1,0,0), ..., (6,8,0)
objp = np.zeros((chessboard_size[0] * chessboard_size[1], 3), np.float32)
objp[:, :2] = np.mgrid[0:chessboard_size[0], 0:chessboard_size[1]].T.reshape(-1, 2)

# Arrays to store object points and image points from all images
objpoints = []  # 3D points in real-world space
imgpoints = []  # 2D points in image plane

# Load all calibration images
images = glob.glob("1.jpg")  # Change this to load multiple images

if not images:
    print("Error: No calibration images found!")
    exit()

gray = None  # Initialize gray to avoid NameError

for fname in images:
    img = cv2.imread(fname)
    if img is None:
        print(f"Error: Could not load image {fname}")
        continue

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Find the chessboard corners
    ret, corners = cv2.findChessboardCorners(gray, chessboard_size, None)

    if ret:
        objpoints.append(objp)
        imgpoints.append(corners)

        # Draw and display the corners
        cv2.drawChessboardCorners(img, chessboard_size, corners, ret)
        cv2.imshow("Corners", img)
        cv2.waitKey(500)

cv2.destroyAllWindows()

# Ensure at least one valid calibration image exists
if not objpoints or gray is None:
    print("Error: No valid images with detected chessboard corners.")
    exit()

# Perform camera calibration
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

print("Camera Matrix:\n", mtx)
print("Distortion Coefficients:\n", dist)

# Save calibration data
np.save("camera_matrix.npy", mtx)
np.save("dist_coeffs.npy", dist)

print("Camera calibration successful. Data saved.")




Camera Matrix:
 [[2.13672283e+03 0.00000000e+00 6.19922564e+02]
 [0.00000000e+00 2.10347810e+03 4.53762111e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
Distortion Coefficients:
 [[ 2.18872502e-01 -1.67451893e+01 -1.48993478e-03  1.13496182e-04
   2.34006294e+02]]
Camera calibration successful. Data saved.
